/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_ndkdemo_CounterNative */

#ifndef _Included_com_example_ndkdemo_CounterNative
#define _Included_com_example_ndkdemo_CounterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_CounterNative
 * Method:    nativeSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_CounterNative_nativeSetup
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkdemo_CounterNative
 * Method:    nativeExecute
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_CounterNative_nativeExecute
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_ndkdemo_CounterNative
 * Method:    nativeExe
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_CounterNative_nativeExe
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
