/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_ndkdemo_CounterNative2 */

#ifndef _Included_com_example_ndkdemo_CounterNative2
#define _Included_com_example_ndkdemo_CounterNative2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_CounterNative2
 * Method:    nativeSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_CounterNative2_nativeSetup
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkdemo_CounterNative2
 * Method:    nativeExe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkdemo_CounterNative2_nativeExe
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
