/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_example_ndkdemo_NativeExcute */

#ifndef _Included_com_example_ndkdemo_NativeExcute
#define _Included_com_example_ndkdemo_NativeExcute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkdemo_NativeExcute
 * Method:    execute
 * Signature: (Ljava/lang/Long;)I
 */
JNIEXPORT jint JNICALL Java_com_example_ndkdemo_NativeExcute_execute
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
